{{- if .Values.KialiIngress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ .Values.KialiIngress.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
{{ toYaml .Values.KialiIngress.rules | indent 4 }}
{{- end }}