{{- if .Values.JaegerIngress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: {{ .Values.JaegerIngress.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
{{ toYaml .Values.JaegerIngress.rules | indent 4 }}
{{- end }}