nameOverride: kiali
fullnameOverride: kiali
namespace: istio-system
istioNamespace: istio-system
istioComponentNamespaces:
  prometheus: prometheus
deployment:
  ingress:
    enabled: false
  namespace: istio-system
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  replicas: 1
  nodeSelector:
    servicemesh: enabled
  serviceType: ClusterIP
  additionalServiceYaml:
    nodePort: 30010
auth:
  strategy: anonymous
externalServices:
  customDashboards:
    enabled: true
  istio:
    configMapName: "istio-1-9-1"
    istioIdentityDomain: "svc.cluster.local"
  prometheus:
    url: http://prometheus-kube-prometheus-prometheus.prometheus.svc:9090
  tracing:
    enabled: true
    namespaceSelector: true
    inClusterUrl: http://jaeger-operator-jaeger-query.istio-system:16686
  grafana:
    auth:
      password: password
      type: basic
      useKialiToken: false
      username: admin
    enabled: true
    inClusterUrl: http://grafana.istio-system.svc:3000
    url: http://k1-master01:30099
server:
  metricsEnabled: true
  metricsPort: 9090
  port: 20001
  webRoot: /kiali

KialiIngress:
  enabled: true
  namespace: istio-system
  rules:
  - host: kiali.k1-node01
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kaili
            port:
              number: 20001