---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-controlplane-monitor
  namespace: {{ .Values.namespace  }}
  labels:
    monitoring: istio-controlplane
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
    - {key: istio, operator: In, values: [pilot]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: {{ .Values.istio.interval }}
